Cleanup, add type annotations and improve docstrings
UCL/pyCascadia pull request #54
Opened 2021-06-29 08:43 UTC by JamieJQuinn

This PR cleans up some unused flags in `load_source`, adds type annotations where appropriate and broadens the docstrings to act as potential sources for auto-generation of documentation with Sphinx in the near future. The docstrings use [google's style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) for maximum readability and compatibility with Sphinx.

2021-06-29 14:44 UTC, alessandrofelder requested changes
Great work, @JamieJQuinn!
I've made some minor comments for you to consider.

Below are some style points that I may be wrong on (and that probably `black` can take care of?) - we can also just be happy that `black` is happy 😆 

Generally, from looking at the Google style guide, I think that
- the return values and the argument descriptions should be capitalised,
- doc lines should end with a period

and this is not consistently the case,  e.g.
```comment
    Args:
        fname: filename of input grid             # inconsistent
        region: Optional region to crop to.        # correct
 ```
 And similarly for other parts of the docstring.

Very nitpickily, we might want to spell [`netCDF`](https://www.unidata.ucar.edu/software/netcdf/) and [`GeoTiff`](https://earthdata.nasa.gov/esdis/eso/standards-and-references/geotiff) like so in our docstrings, to be consistent with the spelling of their webpages (although `netCDF`/`NetCDF` seem to be used interchangeably to some extent by them?)

2021-06-29 14:44 UTC, alessandrofelder commented on pycascadia/remove_restore.py
> +        grid which should be multiplied by input grid in order to smooth
this docs are very clear 🚀

2021-06-29 14:44 UTC, alessandrofelder commented on scripts/close_boundary.py
> +        description="Add halo surrounding given netcdf file"
```suggestion
        description="Add piecewise halo surrounding given netcdf file"
```
Just a suggestion, not sure it's the best. I wonder whether just "halo" implies continuity all around the grid.

2021-08-04 09:46 UTC, JamieJQuinn commented on pycascadia/grid.py
> +    def as_xyz(self) -> pandas.DataFrame:
My thinking is that it's conceptually a collection of xyz data points, as opposed to a grid. We've broadly kept the terms grid -> xarray.DataArray and xyz -> pandas.DataFrame so I don't think it's too important to make the distinction that it's a dataframe. Perhaps in the future if another xyz representation ever gets added, the distinction would be more important?

2021-08-04 11:06 UTC, alessandrofelder commented on pycascadia/grid.py
> +    def as_xyz(self) -> pandas.DataFrame:
OK, right, I am happy with that.

2021-08-04 11:08 UTC, alessandrofelder approved these changes
Awesome 💯
I'll leave the merging honours to you, @JamieJQuinn :)

2021-08-04 11:15 UTC, merged